config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :messages do
    collection do
      get 'received' => 'messages#index'
      get 'sent'
    end
  end
  resources :sessions, only: [:new, :create] # equivalent: get 'sign_up' => 'sessions#new' get 'sign_in' => 'sessions#create'
  resources :users
  root 'home#index'
  delete 'sign_out' => 'sessions#destroy'
  # We keep sessions#create for our regular login.
  # Let's use sessions#callback for Facebook login
  get 'auth/:provider/callback' => 'sessions#callback' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  # belongs_to :model
  # equivalent
  # belongs_to :model, class_name: 'Model', foreign_key: 'model_id'
  # in that case, model = Model.find_by_id(id: model_id)
  # if foreign_key does not exist, Rails will get the name after belongs_to
  # add _id and use it foreign key
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  mount_uploader :image, ImageUploader
  validates :subject, :body, presence: true
  validates_processing_of :image
  validate :image_size_validation

  def unread
    read_at ? false : true
  end

  private
    def image_size_validation
      errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
    end

  # Fake messages generator for testing purpose
  # def self.generate_messages
  #   5.times do
  #     Message.create(subject: Faker::Lorem.word,
  #                    body: Faker::Lorem.sentence,
  #                    sender_id: rand(7..11),
  #                    recipient_id: 6)
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  validates :email, presence: true, uniqueness: true
  has_many :friendships
  has_many :friends, through: :friendships

  def to_s
    name
  end

  def self.from_omniauth(auth)
    # Check out the Auth Hash function at https://github.com/mkdynamic/omniauth-facebook#auth-hash
    # and figure out how to get email for this user.
    # Note that Facebook sometimes does not return email,
    # in that case you can use facebook-id@facebook.com as a workaround
    email = auth[:info][:email] || "#{auth[:uid]}@facebook.com"
    name = auth[:info][:name] || "Username"
    user = where(email: email).first_or_initialize
    # Set other properties on user here. Just generate a random password. User does not have to use it.
    # You may want to call user.save! to figure out why user can't save
    user.name = name
    user.email = email
    user.password = SecureRandom.base64(10)
    # Finally, return user
    user.save! && user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?, :require_signin

  def current_user
    # @current_user is always nil at the beginning
    # of the request (in action or view). 
    # return code line just prevents calling DB
    # twice or more. you will always call DB once
    return @current_user if @current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
    # Equivalent
    # @current_user ||= User.find(session[:user_id])
  end

  def require_signin
    if !signed_in?
      flash[:warning] = "You must signed in to see this page"
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    @backward_friendship = Friendship.new(user_id: params[:friend_id], friend_id: current_user.id)
    if @friendship.save and @backward_friendship.save
      flash[:success] = 'Added friend'
      redirect_to user_path(id: current_user.id)
    else
      flash[:error] = 'Cannot add friend'
      redirect_to users_path
    end
  end

  def destroy
    @friendship = Friendship.find_by(user_id: current_user.id, friend_id: params[:friend_id])
    @backward_friendship = Friendship.find_by(user_id: params[:friend_id], friend_id: current_user.id)
    @friendship.destroy
    @backward_friendship.destroy
    flash[:info] = 'Aww, you two no longer friend. How sad !!!'
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to messages_path
    else
      redirect_to new_user_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show]

  def index
    @messages = current_user.received_messages
  end

  def sent
    @messages = current_user.sent_messages
  end

  def show
    if current_user.id == @message.recipient_id
      @message.read_at = Time.now
      @message.save
    else
      flash[:error] = 'You have no authorize to read this message'
      redirect_to new_session_path
    end
  end

  def new
    @users = current_user.friends
    @message = Message.new
  end

  def create
    @users = current_user.friends
    @message = Message.new(message_params)
    @message.sender = current_user
    if @message.save
      flash[:success] = 'Message sent'
      redirect_to root_path
    else
      flash[:error] = 'There is some problem'
      render 'new'
    end
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:subject, :body, :recipient_id, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      if @user.authenticate(params[:password])
        flash.now[:success] = 'Signed in successfully'
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash.now[:error] = 'Wrong password'
        render 'new'
      end
    else
      flash.now[:error] = 'User not found'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: {info: 'Signed out'}
  end

  def callback
    if user = User.from_omniauth(env["omniauth.auth"])
      flash[:success] = 'Signed in by Facebook successfully'
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Error while signing in by Facebook. Let's register"
      redirect_to new_user_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, only: [:index]

  def index
    @friends_id = current_user.friends.all.select(:id)
    @users = User.where.not(id: @friends_id).where.not(id: current_user.id)  # remain users who are not friend with current user
  end

  def new
    @user = User.new(email: params[:email])
  end

  def show
    @users = current_user.friends # Friendships of current user
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Welcome! #{@user.name}"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def semantic_class_for flash_type
    { success: 'green', info: 'blue', error: 'red', warning: 'yellow' }[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "ui #{semantic_class_for(msg_type)} message") do
        content_tag(:i, nil, class: 'close icon') + content_tag(:div, message, class: 'header')
      end
    end.join.html_safe
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1 class="ui center aligned icon header">
  <i class="green comments icon"></i>
  TinyChat
</h1>

<div class="ui hidden divider"></div>

app/views/layouts/_navbar.html.erb
<div class="ui large green inverted menu">
  <a class="ui active item" href=<%= root_path %> >TinyChat</a>
  <a class="ui item" href=<%= users_path %> >Users</a>
  <div class="right menu">
    <% if current_user %>
      <a class="ui active item"><%= current_user %></a>
      <%= link_to "Inbox", messages_path, class: 'ui item' %>
      <%= link_to "Friends", user_path(id: current_user.id), class: 'ui item' %>
      <%= link_to "Sign Out", sign_out_path, method: 'delete', class: 'ui item' %>
    <% else %>
      <%= link_to 'Sign Up', new_user_path, class: 'ui item' %>
      <%= link_to 'Sign In', new_session_path, class: 'ui item' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiny Chat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<% if @messages.empty? %>
  <div class="ui yellow message">Hey, you have not sent any messages lately</div>
<% end %>
<table class="ui large celled green table">
  <thead>
    <tr>
      <th class="three wide">Sender</th>
      <th class="five wide">Subject</th>
      <th class="four wide">Sent at</th>
      <th class="four wide">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr class=<%= message.unread ? "positive" : "" %>>
        <td><%= message.sender %></td>
        <td><%= message.subject %></td>
        <td><%= message.created_at.strftime("%d %b %Y %l:%M %p") %></td>
        <% if received %>
          <td class="center aligned">
            <% if message.unread %>
              <a href="<%= message_path(message) %>"><button class="ui active green button">Unread</button></a>
            <% else %>
              <button class="ui button" onclick="infoDisplay()">Read</button>
            <% end %>
          </td>
        <% else %>
          <td><%= message.unread ? 'Unread' : message.read_at.strftime("%d %b %Y %l:%M %p") %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messages/_header.html.erb
<div class="ui grid">
  <div class="four wide column">
    <a href="<%= new_message_path %>"><button class="ui large red button">New Message</button></a>
  </div>
</div>

<div class="ui hidden divider"></div>

app/views/messages/_message.html.erb
<% if @messages.empty? %>
  <div class="ui yellow message"><%= received ? 'Aww. No message, no friends?' : 'Hey, you have not sent any messages lately'%></div>
<% end %>
<table class="ui large celled green table">
  <thead>
    <tr>
      <th class="three wide"><%= received ? 'Sender' : 'Recipient' %></th>
      <th class="five wide">Subject</th>
      <th class="four wide">Sent at</th>
      <th class="four wide">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr class=<%= message.unread ? "positive" : "" %>>
        <td><%= received ? message.sender : message.recipient %></td>
        <td><%= message.subject %></td>
        <td><%= message.created_at.strftime("%d %b %Y %l:%M %p") %></td>
        <% if received %>
          <td class="center aligned">
            <% if message.unread %>
              <a href="<%= message_path(message) %>"><button class="ui active green button">Unread</button></a>
            <% else %>
              <button class="ui button" onclick="infoDisplay()">Read</button>
            <% end %>
          </td>
        <% else %>
          <td><%= message.unread ? 'Unread' : message.read_at.strftime("%d %b %Y %l:%M %p") %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messages/_sidemenu.html.erb
<% if received %>
  <div class="ui large vertical menu">
    <a href="<%= received_messages_path %>" class="active green item">
      Inbox
      <% if current_user.received_messages.where(read_at: nil).any? %>
        <div class="ui green left pointing label"><%= current_user.received_messages.where(read_at: nil).count %></div>
      <% end %>
    </a>
    <a href="<%= sent_messages_path %>" class="item">
      Sent
      <div class="ui left pointing label"><%= current_user.sent_messages.count %></div>
    </a>
  </div>
<% else %>
  <div class="ui large vertical menu">
    <a href="<%= received_messages_path %>" class="item">
      Inbox
      <% if current_user.received_messages.where(read_at: nil).any? %>
        <div class="ui left pointing label"><%= current_user.received_messages.where(read_at: nil).count %></div>
      <% end %>
    </a>
    <a href="<%= sent_messages_path %>" class="active green item">
      Sent
      <div class="ui green left pointing label"><%= current_user.sent_messages.count %></div>
    </a>
  </div>
<% end %>

app/views/messages/index.html.erb
<h1 class="ui center aligned icon header">
  <i class="green inbox icon"></i>
  Inbox
</h1>

<%= render 'messages/header' %>

<div class="ui grid">
  <div class="four wide column">
    <%= render 'messages/sidemenu', received: true %>
  </div>
  <div class="twelve wide column">
    <%= render 'messages/message', received: true %>
  </div>
</div>

<div class="ui small basic modal">
  <div class="ui icon header">
    <i class="archive icon"></i>
    Read Messages
  </div>
  <div class="content">
    <p>You just have one time to read this message.</p>
  </div>
  <div class="actions">
    <div class="ui green ok inverted button">
      <i class="checkmark icon"></i>
      OK
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<h1>New</h1>

<%= form_for @message do |f| %>
  <% if @message.errors.present? %>
    <div class="ui red message"><%= @message.errors.full_messages.to_sentence %></div>
  <% end %>

  <div class="ui large form">
    <div class="field">
      <%= f.label :recipient_id %>
      <%= f.select :recipient_id, @users.map { |u| [u.email, u.id] }, class: 'ui search dropdown' %>
    </div>
    <div class="field">
      <%= f.label :subject %>
      <%= f.text_field :subject %>
    </div>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <%= f.submit "Send", :disable_with => 'Sending...', class: 'ui green button' %>
  </div>
  
<% end %>

app/views/messages/sent.html.erb
<h1 class="ui center aligned icon header">
  <i class="green mail outline icon"></i>
  Sent
</h1>

<%= render 'messages/header' %>

<div class="ui grid">
  <div class="four wide column">
    <%= render 'messages/sidemenu', received: false %>
  </div>
  <div class="twelve wide column">
    <%= render 'messages/message', received: false %>
  </div>
</div>

app/views/messages/show.html.erb
<h1>New</h1>

<%= render 'messages/header' %>

<div class="ui grid">
  <div class="four wide column">
    <%= render 'messages/sidemenu', received: true %>
  </div>
  <div class="twelve wide column">
    <h1 class="ui header"><%= @message.subject %></h1>
    <div class="ui divider"></div>
    <h3 class="ui header">
      <div class="ui sub header">From: 
        <div class="ui green label"><%= @message.sender %></div>
        <div class="ui basic label"><%= @message.created_at.strftime("%b %d, %Y") %></div>
      </div>
    </h3>
    <div class="ui large message">
      <p><%= @message.body %></p>
      <% if @message.image.present? %>
        <p><%= image_tag(@message.image, height: 320, width: 240) %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="ui center aligned icon header">
  <i class="green users icon"></i>
  Users
</h1>

<div class="ui three cards">
  <% @users.each do |user| %>
    <div class="card">
      <div class="content">
        <div class="header"><%= user.name %></div>
        <div class="description"><%= user.email %></div>
      </div>
      <%= link_to 'Add Friend', friendships_path(friend_id: user), method: 'post', class: 'ui green attached button' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="ui grid">
  <div class="four wide column"></div>

  <div class="eight wide column">
    <h1 class="ui center aligned icon header">
      <i class="green add user icon"></i>
      Sign Up
    </h1>

    <div class="ui large attached positive message">
      <div class="header">
        Welcome to our site!
      </div>
      <p>Fill out the form below to sign-up for a new account</p>
    </div>

    <div class="ui large form attached fluid segment">
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="ui yellow message"><%= @user.errors.full_messages.to_sentence %></div>
        <% end %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: 'Name' %>
        </div>
        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email, placeholder: 'Email' %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: 'Password' %>
        </div>
        <%= f.submit "Register", class: 'ui large green button' %>
      <% end %>
    </div>
    <div class="ui large bottom attached warning message">
      <i class="icon help"></i>
      Already signed up? <a href="<%= new_session_path %>">Sign in here</a> instead.
    </div>
  </div>

  <div class="four wide column"></div>
</div>

app/views/users/show.html.erb
<h1 class="ui center aligned icon header">
  <i class="green users icon"></i>
  Friends
</h1>

<div class="ui three cards">
  <% @users.each do |user| %>
    <div class="card">
      <div class="content">
        <div class="header"><%= user.name %></div>
        <div class="description"><%= user.email %></div>
      </div>
      <%= link_to 'Unfriend', friendship_path(friend_id: user), method: :delete, data: { confirm: 'Are you sure' }, class: 'ui red attached button' %>
    </div>
  <% end %>
</div>